### ISSUE TITLE
Licens

### ISSUE THREAD

**Issue by neic** [TK-IT/tket-latex#6]
Målet er at få alle gamle bidragsydere til at overdrage deres bidrag til forening TÅGEKAMMERET. BEST kan derefter bestemme hvad der skal ske med ophavsretten til koden (sikkert på baggrund af en anbefaling fra TK-IT).

Vi har en beerware licens på nogle af de andre projekter. Jeg syntes at vi skal passe lidt mere på det her. Det er ikke nødvendigt at give en offentlig kode en licens, så mit forslag er at kode bare er ©TÅGEKAMMRET, stillesigende kræve at bidragsydere overføre deres bidrag til foreningen og implicit lade BEST skal tage stilling til alle genbrug af koden.

**Comment by Mortal** [comment]
Jeg synes vi skal skrive eksplicit at man skal kontakte os hvis man ønsker at genbruge koden. Jeg har skrevet noget i PR #11 -- kommentarer er velkomne.
