### ISSUE TITLE
Problemer med make

### ISSUE THREAD

**Issue by jakobmoss** [TK-IT/tket-latex#9]
Det er ikke muligt at køre `make` uden at have `tket`-pakken installeret på systemet i forvejen. Hvis man gør, fejler `latexmk` med beskeden om, at `tket.sty` ikke findes. Det er sikkert okay, da man nok ikke kan finde på at bygge arkivet uden at have `tket` installeret (med mindre man åbenbart er mig, som har glemt at installere den på sin arbejdscomputer).

Et mere alvorligt problem er dog, at selv efter installationen af `tket` bliver `make` stadig ikke korrekt færdig. Den kommer længere, men stopper ved:
```
# Remove dependencies inadvertently picked up from minted by latexmk
sed -i -e 's@doc/tket-doc\.\(aex\|w18\)@@' doc/tket-doc.d
make: *** No rule to make target `doc/tket-doc.aex', needed by `doc/tket-doc.d'.  Stop.
```

**Comment by neic** [comment]
Hvis du bare vil installere pakken kan du hente et release istedet: https://github.com/TK-IT/tket-latex/releases
(Det burde dokumenteres: #10 )

**Comment by jakobmoss** [comment]
Det er også det jeg har gjort for at installere pakken. Det virkede i øvrigt helt perfekt!

Men når det så er sagt, er det så ikke stadig mystisk at jeg ikke kan bygge den selv fra source?

**Comment by neic** [comment]
Bestemt. Det her er en reel bug.

**Comment by neic** [comment]
@Mortal hvad siger du til følgende? Det var den eneste måde jeg kunne få både `latexmk` og `make` til at være glad med en anden `TEXINPUTS`. Den løser stadig ikke problemet med at der ikke bliver kørt noget hvis nogle af filerne i `src` bliver ændret.

```make
all: tket.tds.zip

tket.tds.zip: doc/tket-doc.pdf
	mkdir -p tket.tds/doc/tex/latex/tket
	cp doc/tket-doc.pdf doc/*.tex tket.tds/doc/tex/latex/tket
	mkdir -p tket.tds/tex/latex/tket
	cp src/*.eps src/*.pdf src/tket.sty tket.tds/tex/latex/tket
	zip -r tket.tds.zip tket.tds
	rm -r tket.tds

doc/tket-doc.pdf: %.pdf: %.tex
	cd doc && \
	TEXINPUTS=../src/: \
	latexmk -pdf -shell-escape -deps-out=$*.d $*.tex

# File containing dependencies, generated by latexmk
doc/tket-doc.d: %.d: %.tex
	cd doc && \
	TEXINPUTS=../src/: \
	latexmk -pdf -shell-escape -deps-out=tket-doc.d tket-doc.tex
	# Remove dependencies inadvertently picked up from minted by latexmk
	sed -i -e '/^[ ^I]*tket-doc\.\(aex\|w18\)/ d' doc/tket-doc.d

include doc/tket-doc.d
```

**Comment by Mortal** [comment]
@neic Det virker ikke for mig:

```
rav@alcyone:~/work/tkit/tket-latex$ rm -f doc/tket-doc.{d,pdf} tket.tds.zip 
rav@alcyone:~/work/tkit/tket-latex$ make >/dev/null 2>/dev/null
rav@alcyone:~/work/tkit/tket-latex$ echo $?
0
rav@alcyone:~/work/tkit/tket-latex$ touch src/tket.sty 
rav@alcyone:~/work/tkit/tket-latex$ make
make: Nothing to be done for 'all'.
```

Make ser ikke at `src/tket.sty` er ændret fordi stierne i `doc/tket-doc.d` er relative til `doc/tket-doc.tex`, men de skal være relative til `Makefile`, dvs. der skal stå `doc/../src/tket.sty` i stedet for `../src/tket.sty` is `tket-doc.d`-filen -- og derfor indeholder den nuværende Makefile en linje der prøver at tilføje "doc/" foran alle relative stier.

Hvad med bare at tilføje "TEXINPUTS=../src/" til den nuværende makefile? Hvad med følgende makefile:

```make
all: tket.tds.zip

DOC_SOURCES = $(wildcard doc/*.tex)
TEX_SOURCES = $(wildcard src/*.eps src/*.pdf src/tket.sty)

tket.tds.zip: doc/tket-doc.pdf $(DOC_SOURCES) $(TEX_SOURCES)
	mkdir -p tket.tds/doc/tex/latex/tket
	cp doc/tket-doc.pdf $(DOC_SOURCES) tket.tds/doc/tex/latex/tket
	mkdir -p tket.tds/tex/latex/tket
	cp $(TEX_SOURCES) tket.tds/tex/latex/tket
	zip -r tket.tds.zip tket.tds
	rm -r tket.tds

doc/tket-doc.pdf: doc/tket-doc.tex
	TEXINPUTS=../src/: \
	latexmk -cd -pdf -shell-escape doc/tket-doc.tex

# File containing dependencies, generated by latexmk
doc/tket-doc.d: doc/tket-doc.tex
	TEXINPUTS=../src/: \
	latexmk -cd -pdf -shell-escape -deps-out=doc/tket-doc.d doc/tket-doc.tex
	# Remove dependencies inadvertently picked up from minted by latexmk
	sed -i -e '/_minted-tket-doc/ d' $@
	# Add doc/ in front of all relative paths
	sed -i -e 's@^\( *\)\([^\\# /]\)@\1doc/\2@' $@
	# Remove dependencies inadvertently picked up from minted by latexmk
	sed -i -e 's@doc/tket-doc\.\(aex\|w18\)@@' $@

include doc/tket-doc.d
```
